name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Set up JDK 17 (Temurin is an OpenJDK distribution)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build with Maven (skip tests for speed, or remove -DskipTests to run tests)
      - name: Run Unit & Integration Tests
        run: |
          chmod +x mvnw
          ./mvnw clean test verify

      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 5. Define environment variables for Docker tags
      - name: Define Docker Image Tag
        run: echo "IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/notification-service:${{ github.sha }}" >> $GITHUB_ENV

      # 6. Build Docker Image (commit SHA tag)
      - name: Build Docker Image
        run: |
          echo "Building Docker image with tag: $IMAGE_TAG"
          docker build -t $IMAGE_TAG .

      # 7. Push Docker Image (commit SHA tag)
      - name: Push Docker Image
        run: |
          echo "Pushing Docker image: $IMAGE_TAG"
          docker push $IMAGE_TAG

      # 8. Tag and push 'latest' (Optional)
      - name: Tag and Push 'latest'
        run: |
          docker tag $IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest
